language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install:
  - go get github.com/kdar/factorlog
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/securecookie
  - go get github.com/gorilla/sessions