language: go

go:
  - 1.4
  - tip

install:
  - go get -v ./...
  - go get -u -f -v golang.org/x/crypto/bcrypt
  - go get -u -f -v gopkg.in/boj/redistore.v1
  - go get -u -f -v github.com/smartystreets/assertions
  - go get -u -f -v github.com/smartystreets/goconvey

before_script:
  - echo "GRANT ALL PRIVILEGES ON *.* TO $DATABASE_USER@localhost IDENTIFIED BY '$DATABASE_PASSWORD';" | mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD
  - mysql --user=$DATABASE_USER --password=$DATABASE_PASSWORD < database/mysql/eveauth_create.sql
  - mysql --user=$DATABASE_USER --password=$DATABASE_PASSWORD < database/mysql/eveauth_testdata.sql