language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

install:
  - go get -d -v ./...
  - go get -d -v golang.org/x/crypto/bcrypt
  - go get -d -v github.com/smartystreets/goconvey

before_script:
  - mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD < database/mysql/eveauth_create.sql
  - mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD < database/mysql/eveauth_testdata.sql